env:
  browser: true
  es2021: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: 
    - ./tsconfig.json
rules:
  semi: off
  quotes:
    - error
    - double
  "@typescript-eslint/semi":
    - error
    - always
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/no-explicit-any": 1
  "@typescript-eslint/no-inferrable-types": 1
  "@typescript-eslint/no-unused-vars": "warn"

